spring:
  datasource:
    username: root
    password: shang19970110
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=EST
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  type-aliases-package: com.new.hrm01.entity